### ISSUE TITLE
Commits aren't being used properly

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [HackTricks-wiki/hacktricks#342]
First of all, thanks for maintaining this project. It's an amazing resource :)

What I wanted to say is that commits aren't being used properly here. Most commit messages are empty:
![2022-05-26 22_47_25-Window](https://user-images.githubusercontent.com/46269721/170612255-f8bedac0-e81e-4413-b98c-1ca495cfa43f.png)
Why do I care? I'm trying to setup an RSS Feed of the commits of this repo. With most commit messages having little to no content, an RSS feed is powerless. Besides that, having empty commit messages goes against all best practices; it makes it harder to track the changes
that are done to a project, and as a consequence also makes it harder to undo them.

All I'm really asking for is that you at least include _the title of the modified section_ in the commit message 🙏

Regards.

**Comment by carlospolop** [comment]
Hi @ItsIgnacioPortal,

It would be nice to have a RSS Feed to notice the changes in hacktricks, unfortunately I don't control those commits.
Those are automatically created by gitbook when I modify the book in the web page, so gitbook should change that.
Let me know if you can see any workaround to set a RSS feed from the commits as I'm also interested.

**Comment by ItsIgnacioPortal** [comment]
I've found that you can add `/commits.atom` to the URL of any repo to get an RSS feed of its commits. This is the feed for this repo: https://github.com/carlospolop/hacktricks/commits.atom

> unfortunately I don't control those commits.
> Those are automatically created by gitbook when I modify the book in the web page, so gitbook should change that.

**Could you make a "bug report" to ask that they add support for setting the commit messages?**

I see three possible solutions: 
- They add a couple of text boxes so you can set both parts of the commit message
- Set the _commit message title_ to the filepaths of the modified file(s).
- Set the commit message to [the contents of the .patch for that commit](https://gist.github.com/emmanueltissera/19d0a8852f000cde13768dd7420a0906). For example, [this is the .patch](https://github.com/torvalds/linux/commit/7e284070abe53d448517b80493863595af4ab5f0.patch) of [this commit](https://github.com/torvalds/linux/commit/7e284070abe53d448517b80493863595af4ab5f0)

Maybe a combination of all three would be best. Like, imagine an "Autocomplete commit messages" setting; that would use the 2nd and 3rd solution. But if you wanted to set the messages manually, you should be able to.

Given that `gitbook` has `git` in its name, I'm surprised that this isn't a feature already. Seems quite essential for a source control system.
 https://docs.gitbook.com/resources/faq/report-bugs

**Comment by ItsIgnacioPortal** [comment]
I've created a [feature request](https://github.com/github/feedback/discussions/17400) so Github will include diffs in the RSS articles of each commit.

Whichever of these two features gets implemented first, should solve our issue. But I still need you to ask gitbook to do their part. I would do it myself, but I'm not very familiar with gitbook, and perhaps you can see a solution that I don't.

**Comment by carlospolop** [comment]
Hey, thats cool, thanks for submitting the feature request!
If you didn't submit the feature request to gitbook I will try it to do myself this week

**Comment by ItsIgnacioPortal** [comment]
> Hey, thats cool, thanks for submitting the feature request! If you didn't submit the feature request to gitbook I will try it to do myself this week

Yeah, I haven't contacted gitbook. Please do that
