### ISSUE TITLE
Add option for "light mode" to the website

### ISSUE THREAD

**Issue by aetios** [HackTricks-wiki/hacktricks#585]
I'm sure this will be a controversial request to make for many people using Hacktricks however I will make it nonetheless. I'm one of those weird guys that prefers light themes over dark, and I was sad to find out that Hacktricks has removed the light theme in favour of a dark version. I would really appreciate an option to switch back to a light version of the site!

**Comment by carlospolop** [comment]
Nowadays gitbook selects your current PC appearance (light or dark) and uses it, so as long as you have selected light appearance in your PC you should see the version with the white background!
