### ISSUE TITLE
API Security Tool Suggestion

### ISSUE THREAD

**Issue by DeliciousBounty** [HackTricks-wiki/hacktricks#593]
Hello @carlospolop ,
After reading your API Security page (https://book.hacktricks.xyz/network-services-pentesting/pentesting-web/web-api-pentesting), I wanted to suggest that you include Cherrybomb which is  an API security tool that audit your API based on an OAS file(the tool written in rust). 
The link to the tool: https://github.com/blst-security/cherrybomb

**Comment by carlospolop** [comment]
Added!
Please, next time consider sending a PR to add the info faster!
