### ISSUE TITLE
[Suggestion] Add Katana on the list of Web Security crawlers / JS parsers

### ISSUE THREAD

**Issue by hasshido** [HackTricks-wiki/hacktricks#596]
Page - https://book.hacktricks.xyz/network-services-pentesting/pentesting-web

Tool - https://github.com/projectdiscovery/katana

Also I recommend checking it out, its kinda cool

Best regards :)

**Comment by carlospolop** [comment]
I thought it was! Please, next time consider sending a PR so it gets added faster!
