### ISSUE TITLE
DC Shadow not creating rogue DC

### ISSUE THREAD

**Issue by RamV2810** [HackTricks-wiki/hacktricks#676]
Hi all, I am trying to create a rogue DC to do a DC Shadow attack in my virtual environment.

I get to NT AUTHORITY\SYSTEM on the PC I want to set as the rogue DC.

But when I run: 
mimikatz # lsadump::dcshadow /object:Administrator /attribute:description /value:check

I get this error:
ERROR kuhl_m_lsadump_dcshadow ; ldap 0x31 (49)

Some credential issue. But I can't figure out. I have been trying for the last two days. Can anyone help...thanks.

**Comment by carlospolop** [comment]
Please, ask in hacking forums, not here
