### ISSUE TITLE
suggestion to add memory automation tool in cloud

### ISSUE THREAD

**Issue by bittib010** [HackTricks-wiki/hacktricks#801]
Im working on a side project on automating Volatility in azure at scale, allowing for multiple dumps automatically parsed and sent to ADX. Would love to see this listed as a tool if you find it worthy: https://github.com/bittib010/AjourVolAutolity

**Comment by carlospolop** [comment]
Could you send a PR to the page to add this tool with a brief summary about the capabilities of the tool and how it works please?
