### ISSUE TITLE
[Suggestion] Section for Industrial Control Systems (ICS) and SCADA Hacking

### ISSUE THREAD

**Issue by PythonHacker24** [HackTricks-wiki/hacktricks#821]
Industrial Control Systems and SCADA Hacking are some of the most important areas of security with relatively less information available. There have been a lot of attacks on that side, and hence, a few case studies can also be added to demonstrate impacts and severity of ICS Hacking.

**Comment by carlospolop** [comment]
Please, send PRs about this, it would be a great addition!
