### ISSUE TITLE
Does the dark mode is gone?

### ISSUE THREAD

**Issue by Wolfvaudou** [HackTricks-wiki/hacktricks#824]
I was checking something as usual on hacktricks for a ctf and my eyes got a violent assault from the light mode. Does the dark mode is gone forever?

**Comment by syedabeerahmed** [comment]
🤣😂

**Comment by carlospolop** [comment]
Nowadays gitbook selects your current PC appearance (light or dark) and uses it, so as long as you have selected light appearance in your PC you should see the version with the white background!
