### ISSUE TITLE
Fix Typo in title of Wmiexec

### ISSUE THREAD

**Issue by mrtzhsmnn** [HackTricks-wiki/hacktricks#876]
There is a typo in the filename and therefore title and url for your great article about WmiExec.

https://book.hacktricks.xyz/windows-hardening/lateral-movement/wmicexec

**Comment by carlospolop** [comment]
thanks! Fixed

**Comment by saibamo** [comment]
Great to see, maybe adding a redirect from the old typo link to the fixed one would be a good idea though.

Because you could break some sources and articles linking back to you.
