### ISSUE TITLE
In case if you get time and want to add these test cases (which are not overlapping)

### ISSUE THREAD

**Issue by iamthefrogy** [HackTricks-wiki/hacktricks#877]
https://frogy.gitbook.io/cyber-frogys-little-world/redopsready

https://frogy.gitbook.io/cyber-frogys-little-world/web-pentest-checklist

**Comment by carlospolop** [comment]
Hi @iamthefrogy , feel free to do a PR to hacktricks with any interesting additions and I'll review it
