### ISSUE TITLE
Broken Wordlist Reference Link in Cache-Deception Special Header

### ISSUE THREAD

**Issue by 0xh7ml** [HackTricks-wiki/hacktricks#888]
Hi,
There is a broken payload reference link on cache-deception page. The referred wordlist link is https://github.com/danielmiessler/SecLists/tree/master/Miscellaneous/web/http-request-headers instead of https://github.com/danielmiessler/SecLists/tree/master/Miscellaneous/Web/http-request-headers

**Comment by carlospolop** [comment]
I've fixed it, thanks for the PRs although  couldn't accept them

**Comment by 0xh7ml** [comment]
:) welcome <3
