### ISSUE TITLE
Why is Nmap half section in Spanish? 

### ISSUE THREAD

**Issue by PythonHacker24** [HackTricks-wiki/hacktricks#939]
<img width="826" alt="Screenshot 2024-09-22 at 11 29 28" src="https://github.com/user-attachments/assets/8da0fb9e-f7d5-40b2-a266-ef4cfabced38">

Why is this written in Spanish in the English Version of the text (all other text is in English)? Can I modify it? 

Also, I would like to format all of the Nmap pages since I have been formally studying Nmap and would like to work on it for Hacktricks.

**Comment by carlospolop** [comment]
Yes please @PythonHacker24 !

**Comment by PythonHacker24** [comment]
#984 Has updated .md file in English. Let me know if there are any Markdown errors. 

Thank you.
